---
title: "PRUEBAS. CIS 2020 análisis"
subtitle: "BORRA ESTE FICHERO"
author: "ImJaviPerez"
date: "Diciembre 2022"
output:
  html_document:
    toc: yes
    toc_depth: '4'
    df_print: paged
  pdf_document:
    number_sections: yes
    toc: yes
    toc_depth: 4
header-includes:
- \usepackage{xcolor}
- \usepackage{framed}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead[RO,RE]{AnálisiS total}
- \fancyfoot{}
- \fancyfoot[RE,LO]{Votos 2020}
- \fancyfoot[LE,RO]{\thepage}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# List of libraries
library(foreign)
library(dplyr)
library(pander)
library(car)
library(ca)

library(gridExtra)
library(grid)
library(lattice)
library(ggplot2)
library(ggrepel)

library(factoextra)

library("RcmdrMisc")
library(cluster)
library(RANN)

library(diverse)
```



```{r}
# We have to filter CIS 2020 data previously. It spends a lot of time for it's calculations, thus we have made those calculations in an other script and now we load those results.

cis_2020_analisys_file <- file.path(getwd(), "cis_2020_analisys_file.RData")
if (file.exists(cis_2020_analisys_file)) {
  load(cis_2020_analisys_file)
}else{
  stop(paste("File", cis_2020_cuisine_file, "DO NOT EXISTS. You must create this file using the script Cuisine.Rmd"))}
```



```{r}
require(ggplot2)
# RVAUTO20_RECODE color codes
scale_color_manual_RVAUTO20_RECODE <- scale_color_manual(breaks = c('PP+C\'s', 'PSE-EE-PSOE', 
                                  'EAJ-PNV', 'EH Bildu', 
                                  'PACMA', 'VOX', 
                                  'Elkarrekin Podemos', 
                                  'Voto nulo', 
                                  'EQUO Berdeak', # 'Otro partido', 
                                  'En blanco', 'No votó/abstención', 'No recuerda', 'N.C.'),
                        values=c("cyan", "orangered", 
                                 "navajowhite", "navajowhite", 
                                 "navajowhite3", "cyan3",
                                 "darkorchid1", 
                                 "yellow", 
                                 "darkgreen", 
                                 "yellow", "yellow", "yellow", "yellow"))

scale_fill_manual_RVAUTO20_RECODE <- scale_fill_manual(breaks = c('PP+C\'s', 'PSE-EE-PSOE', 
                                  'EAJ-PNV', 'EH Bildu', 
                                  'PACMA', 'VOX', 
                                  'Elkarrekin Podemos', 
                                  'Voto nulo', 
                                  'EQUO Berdeak', # 'Otro partido', 
                                  'En blanco', 'No votó/abstención', 'No recuerda', 'N.C.'),
                        values=c("cyan", "orangered", 
                                 "navajowhite", "navajowhite", 
                                 "navajowhite3", "cyan3",
                                 "darkorchid1", 
                                 "yellow", 
                                 "darkgreen", 
                                 "yellow", "yellow", "yellow", "yellow"))

```




```{r cluster_var_tables, echo=FALSE, results='asis'}

# TODO: MOSTRAR ATRIBUTOS PARA TODAS LAS TABLAS: grep(var, pattern = 'P(0-9)')


# Show section with comments an tables by program
#
# Mostrar los resultados de todos los clusters de manera automatizada, por programa
#
# illustrative_vars
EB_vars_not2see <- c("IA_APLAZADA", "IA_MODIFICADA", "IA_SUPERVISADA")

for (n in 1:num_clusters_acm) {
  # Section title
  cat("### Cluster", n, "\n\n")
  
  cat(paste("\nEl cluster número", n, "contiene", length(which(EB_neighbourhood_df$num_cluster == n)), "individuos.\n"))
  
  # Select every column (= variable) of this cluster n
  aux_tbl_indiv_clust_n <- EB_neighbourhood_df[which(EB_neighbourhood_df$num_cluster == n),]
  require(pander)
  panderOptions('knitr.auto.asis', FALSE)
  # pander tries to return a knit_asis class object when run inside knitr, but for loops/vectorized functions this results in incorrect output. The recommended way to solve this is to disable this behavior by setting knitr.auto.asis to FALSE using panderOptions. However, we also need to tell knitr to convert the table on the fly by specifying results='asis' in the chunk options
  
  # Show contingency table with RVAUTO20_RECODE
  require(dplyr)
  str_aux_2 <- paste0("Cluster ", n, ". Votos en 2020 `")
  pander(aux_tbl_indiv_clust_n %>% dplyr::count(RVAUTO20_RECODE, .drop=FALSE), caption = str_aux_2)
  
  
  require(ggplot2)
  aux_tbl <- aux_tbl_indiv_clust_n %>% dplyr::count(EDAD_GRUPO, RVAUTO20_RECODE, .drop=FALSE)
  # Stacked barplot with multiple groups
  print(ggplot(data=aux_tbl, aes(x=EDAD_GRUPO, y=n, fill=RVAUTO20_RECODE)) +
    geom_bar(stat="identity") +
    scale_fill_manual_RVAUTO20_RECODE) + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
  
  cat("\n**Atributos más importantes de este cluster.**\n")
  
  # Subset every row=variable with their entropy of this cluster, n, excluding those with 0 variety
  aux_tbl_vars_clust_n <- subset(EB_neighbourhood_normal_results_df, n_cluster == n & variety !=0)
  # Sort them firstly by entropy and seconly by blau.index
  aux_tbl_vars_clust_n_entrop_sorted <- dplyr::arrange(aux_tbl_vars_clust_n, entropy, blau.index)
  
    
  aux_idx <- aux_tbl_vars_clust_n_entrop_sorted[which(aux_tbl_vars_clust_n_entrop_sorted$entropy < 0.6), "variable"]
  aux_idx <- aux_idx[!(aux_idx %in% EB_vars_not2see)]
  for (k in aux_idx) {
    str_aux_1 <- gsub(pattern = "_GRUPO", replacement = "", k)
    str_aux_2 <- paste0("Cluster ", n, 
                        ". Variable `", k, 
                        "`. ", attributes(cis_2020_df)$variable.labels[colnames(cis_2020_df) == str_aux_1],
                        ". Entropía = ", round(aux_tbl_vars_clust_n_entrop_sorted$entropy[which(aux_idx == k)], digits = 4) )
    pander(aux_tbl_indiv_clust_n %>% dplyr::count(.data[[k]], .drop=FALSE), caption = str_aux_2)
  }
}
```



