---
title: "Mesa 2020 análisis"
subtitle: "Resultados por mesa electoral"
author: "ImJaviPerez"
date: "Mayo 2023"
output:
  html_document:
    toc: yes
    toc_depth: '4'
    df_print: paged
  pdf_document:
    number_sections: yes
    toc: yes
    toc_depth: 4
header-includes:
- \usepackage{xcolor}
- \usepackage{framed}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead[RO,RE]{Mesas electorales}
- \fancyfoot{}
- \fancyfoot[RE,LO]{2020}
- \fancyfoot[LE,RO]{\thepage}
bibliography: BibliografiaME.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message = FALSE)

#    include = FALSE prevents code and results from appearing in the finished file. R Markdown still runs the code in the chunk, and the results can be used by other chunks.
#    echo = FALSE prevents code, but not the results from appearing in the finished file. This is a useful way to embed figures.
#    message = FALSE prevents messages that are generated by code from appearing in the finished file.
#    warning = FALSE prevents warnings that are generated by code from appearing in the finished.
#    fig.cap = "..." adds a caption to graphical results.
#    results='asis' = output as-is, i.e., write raw results from R into the output document
```


```{r include=FALSE}
# Borrar toda las variables
### rm(list=ls())
```

***
```{r}
library(usethis)
use_git_config(user.name = "ImJaviPerez", user.email = "ImJaviPerez@gmail.com")
# usethis::edit_git_config()
```


```{r}
# List of libraries
library(openxlsx)
library(dplyr)
```

```{r}
library(log4r)
# Create a new logger object with create.logger().
logger_mesa <- create.logger()
# Set the logger's file output.
logfile(logger_mesa) <- 'cis_2020_all_cuisine.log'
# Set the current level of the logger.
level(logger_mesa) <- "DEBUG"
#level(logger_mesa) <- "INFO"
# At priority level INFO, a call to debug() won't print anything.
# debug(logger_mesa, 'A Debugging Message')
info(logger_mesa, 'Starting script')
# warn(logger_mesa, 'A Warning Message')
# error(logger_mesa, 'An Error Message')
# fatal(logger_mesa, 'A Fatal Error Message')

```


```{r}
# TODO
# http://destio.us.es/calvo/asignaturas/ge_esco/tutorialusargitgithubrstudio/UsarGitGithubconRStudio.html
# Seguir indicaciones de JRB
```


\pagebreak



```{r}
# Load data from XLSX file
require(openxlsx)
## MESA_XLSX <- "../data/MD3293/Analisis\\ Datos\\ Voto\\ Berdeak\\ EQUO\\ 2023.xlsx"
MESA_XLSX <- "../data/mesas_2020.xlsx"

aux_tbl <- openxlsx::read.xlsx(xlsxFile = MESA_XLSX, sheet = "Votos Mesa")


XLS_empty_cols <- c(cellranger::letter_to_num("X"),
                    cellranger::letter_to_num("AU"),
                    cellranger::letter_to_num("BL"),
                    cellranger::letter_to_num("CD"),
                    cellranger::letter_to_num("CW"),
                    cellranger::letter_to_num("DO"))
XLS_info_cols <- c(cellranger::letter_to_num("A"):cellranger::letter_to_num("EE"))
require(dplyr)
XLS_info_cols <- XLS_info_cols[!(XLS_info_cols %in% XLS_empty_cols)]
```


Número de columnas con información: 
```{r echo=FALSE, results='asis'}
cat(length(XLS_info_cols), ".", sep = "")
```

```{r}
# rename columns
# Get colnames and first row
aux_str <- paste0(colnames(aux_tbl), ".", aux_tbl[1,])
# Replace 2 dots by nothing
aux_str <- gsub(pattern = "\\.\\.", replacement = "", x=aux_str)
# Replace blanks with underscores
aux_str <- gsub(pattern = " ", replacement = "_", x=aux_str)
# Replace ' with nothing
aux_str <- gsub(pattern = "\\'", replacement = "", x=aux_str)

if (length(aux_str[duplicated(aux_str)]) != 0){
  stop("Columnas con nombre duplicado")
}
# Create new dataframe
mesa_votos_df <- aux_tbl[-1,]
# Rename columns
colnames(mesa_votos_df) <- aux_str

# TODO: COLUMNAS 1:7 Y columnas terminan en "MESA: son factor. RESTO SON numeric

```

```{r}
# Create dataframe with results
mesa_results_df <- mesa_votos_df[,1:7]

class(mesa_votos_df$`AUT2020.EQUO_BERDEAK-VERDES`)
mesa_votos_df$`AUT2020.EQUO_BERDEAK-VERDES`/mesa_votos_df$AUT2020.Censo
```






```{r save_variables}
info(logger_mesa, 'Ending script')
```



***

\pagebreak


---
